import Foundation

enum KnownTags {
    static let freeformTags: Set<String> = [
        "all human",
        "alpha/beta/omega dynamics",
        "alternate universe",
        "alternate universe - canon divergence",
        "alternate universe - coffee shops & cafés",
        "alternate universe - college/university",
        "alternate universe - high school",
        "alternate universe - human",
        "alternate universe - modern setting",
        "alternate universe - modern",
        "alternate universe - no powers",
        "alternate universe - soulmates",
        "angst",
        "angst with a happy ending",
        "bickering",
        "bottom!harry",
        "canon compliant",
        "canon divergence",
        "case fic",
        "character study",
        "coffee shop au",
        "comfort",
        "coming out",
        "crack",
        "crossover",
        "domestic fluff",
        "drabble",
        "enemies to friends to lovers",
        "enemies to lovers",
        "established relationship",
        "everyone is alive",
        "everyone is queer",
        "fake dating",
        "fake relationship",
        "fake/pretend relationship",
        "fantasy",
        "first kiss",
        "first time",
        "fix-it",
        "fix-it of sorts",
        "fluff",
        "fluff and angst",
        "fluff and humor",
        "found family",
        "friends to lovers",
        "future fic",
        "getting together",
        "happy ending",
        "humor",
        "hurt/comfort",
        "internalized homophobia",
        "kid fic",
        "love confessions",
        "marriage proposal",
        "married couple",
        "miscommunication",
        "modern au",
        "mpreg",
        "mutual pining",
        "no smut",
        "non-binary character",
        "omegaverse",
        "one shot",
        "oneshot",
        "original character(s)",
        "pining",
        "pining and porn",
        "polyamory",
        "post-canon",
        "pre-canon",
        "pre-relationship",
        "pwp",
        "queer themes",
        "road trips",
        "roommates",
        "second chances",
        "secret relationship",
        "sharing a bed",
        "slow burn",
        "smut",
        "soft",
        "soulmates",
        "strangers to lovers",
        "time travel",
        "trans character",
        "trans female character",
        "trans male character",
        "tropes",
        "tw: depression",
        "unrequited love",
        "vampires",
        "werewolves",
        "whump",
        "5+1 things",
    ]

    static let categoryAliases: [String: AO3SearchFilters.Category] = [
        "f/f": .ff,
        "femslash": .ff,
        "f/m": .fm,
        "het": .fm,
        "gen": .gen,
        "m/m": .mm,
        "slash": .mm,
        "multi": .multi,
        "other": .other,
    ]

    static let ratingAliases: [String: AO3SearchFilters.Rating] = [
        "general": .general,
        "general audiences": .general,
        "g": .general,
        "teen": .teen,
        "teen and up": .teen,
        "t": .teen,
        "mature": .mature,
        "m": .mature,
        "explicit": .explicit,
        "e": .explicit,
        "not rated": .notRated,
        "unrated": .notRated,
    ]

    static let warningAliases: [String: AO3SearchFilters.ArchiveWarning] = [
        "no archive warnings apply": .noWarningsApply,
        "no warnings apply": .noWarningsApply,
        "no warnings": .noWarningsApply,
        "creator chose not to use archive warnings": .chooseNotToUse,
        "choose not to use warnings": .chooseNotToUse,
        "cnow": .chooseNotToUse,
        "graphic depictions of violence": .graphicViolence,
        "graphic violence": .graphicViolence,
        "major character death": .majorCharacterDeath,
        "mcd": .majorCharacterDeath,
        "character death": .majorCharacterDeath,
        "rape/non-con": .rapeNonCon,
        "rape non-con": .rapeNonCon,
        "noncon": .rapeNonCon,
        "non-con": .rapeNonCon,
        "underage": .underage,
    ]

    static let languageAliases: [String: String] = [
        "english": "en",
        "in english": "en",
        "spanish": "es",
        "in spanish": "es",
        "en español": "es",
        "french": "fr",
        "in french": "fr",
        "en français": "fr",
        "german": "de",
        "in german": "de",
        "auf deutsch": "de",
        "russian": "ru",
        "in russian": "ru",
        "chinese": "zh",
        "in chinese": "zh",
        "japanese": "ja",
        "in japanese": "ja",
        "korean": "ko",
        "in korean": "ko",
        "portuguese": "pt",
        "italian": "it",
    ]
}
