import Foundation

enum KnownTags {
    static let freeformTags: Set<String> = [
        "all human",
        "alpha/beta/omega dynamics",
        "alternate universe",
        "alternate universe - canon divergence",
        "alternate universe - coffee shops & cafés",
        "alternate universe - college/university",
        "alternate universe - high school",
        "alternate universe - human",
        "alternate universe - modern setting",
        "alternate universe - modern",
        "alternate universe - no powers",
        "alternate universe - soulmates",
        "angst",
        "angst with a happy ending",
        "bickering",
        "bottom!harry",
        "canon compliant",
        "canon divergence",
        "case fic",
        "character study",
        "coffee shop au",
        "comfort",
        "coming out",
        "crack",
        "crossover",
        "domestic fluff",
        "drabble",
        "enemies to friends to lovers",
        "enemies to lovers",
        "established relationship",
        "everyone is alive",
        "everyone is queer",
        "fake dating",
        "fake relationship",
        "fake/pretend relationship",
        "fantasy",
        "first kiss",
        "first time",
        "fix-it",
        "fix-it of sorts",
        "fluff",
        "fluff and angst",
        "fluff and humor",
        "found family",
        "friends to lovers",
        "future fic",
        "getting together",
        "happy ending",
        "humor",
        "hurt/comfort",
        "internalized homophobia",
        "kid fic",
        "love confessions",
        "marriage proposal",
        "married couple",
        "miscommunication",
        "modern au",
        "mpreg",
        "mutual pining",
        "no smut",
        "non-binary character",
        "omegaverse",
        "one shot",
        "oneshot",
        "original character(s)",
        "pining",
        "pining and porn",
        "romance",
        "drama",
        "friendship",
        "comedy",
        "tragedy",
        "adventure",
        "family",
        "horror",
        "mystery",
        "polyamory",
        "post-canon",
        "pre-canon",
        "pre-relationship",
        "pwp",
        "queer themes",
        "road trips",
        "roommates",
        "second chances",
        "secret relationship",
        "sharing a bed",
        "slow burn",
        "smut",
        "soft",
        "soulmates",
        "strangers to lovers",
        "time travel",
        "trans character",
        "trans female character",
        "trans male character",
        "tropes",
        "tw: depression",
        "unrequited love",
        "vampires",
        "werewolves",
        "whump",
        "5+1 things",
    ]

    static let categoryAliases: [String: AO3SearchFilters.Category] = [
        "f/f": .ff,
        "femslash": .ff,
        "f/m": .fm,
        "het": .fm,
        "gen": .gen,
        "m/m": .mm,
        "slash": .mm,
        "multi": .multi,
        "other": .other,
    ]

    static let ratingAliases: [String: AO3SearchFilters.Rating] = [
        "general": .general,
        "general audiences": .general,
        "g": .general,
        "teen": .teen,
        "teen and up": .teen,
        "t": .teen,
        "mature": .mature,
        "m": .mature,
        "explicit": .explicit,
        "e": .explicit,
        "not rated": .notRated,
        "unrated": .notRated,
    ]

    static let warningAliases: [String: AO3SearchFilters.ArchiveWarning] = [
        "no archive warnings apply": .noWarningsApply,
        "no warnings apply": .noWarningsApply,
        "no warnings": .noWarningsApply,
        "creator chose not to use archive warnings": .chooseNotToUse,
        "choose not to use warnings": .chooseNotToUse,
        "cnow": .chooseNotToUse,
        "graphic depictions of violence": .graphicViolence,
        "graphic violence": .graphicViolence,
        "major character death": .majorCharacterDeath,
        "mcd": .majorCharacterDeath,
        "character death": .majorCharacterDeath,
        "rape/non-con": .rapeNonCon,
        "rape non-con": .rapeNonCon,
        "noncon": .rapeNonCon,
        "non-con": .rapeNonCon,
        "underage": .underage,
    ]

    static let fandomAliases: [String: String] = [
        "harry potter": "Harry Potter - J. K. Rowling",
        "hp": "Harry Potter - J. K. Rowling",
        "marvel cinematic universe": "Marvel Cinematic Universe",
        "mcu": "Marvel Cinematic Universe",
        "the avengers": "The Avengers (Marvel Movies)",
        "twilight": "Twilight Series - Stephenie Meyer",
        "star wars": "Star Wars - All Media Types",
        "star trek": "Star Trek - All Media Types",
        "sherlock": "Sherlock (TV)",
        "supernatural": "Supernatural (TV 2005)",
        "doctor who": "Doctor Who (2005)",
        "buffy": "Buffy the Vampire Slayer (TV)",
        "hunger games": "Hunger Games Series - All Media Types",
        "lord of the rings": "The Lord of the Rings - J. R. R. Tolkien",
        "lotr": "The Lord of the Rings - J. R. R. Tolkien",
        "good omens": "Good Omens (TV)",
        "yuri on ice": "Yuri!!! on Ice (Anime)",
        "my hero academia": "Boku no Hero Academia | My Hero Academia (Anime & Manga)",
        "bnha": "Boku no Hero Academia | My Hero Academia (Anime & Manga)",
        "mha": "Boku no Hero Academia | My Hero Academia (Anime & Manga)",
        "naruto": "Naruto (Anime & Manga)",
        "one piece": "One Piece (Anime & Manga)",
        "haikyuu": "Haikyuu!!",
        "attack on titan": "Shingeki no Kyojin | Attack on Titan",
        "genshin impact": "Genshin Impact (Video Game)",
        "honkai star rail": "Honkai: Star Rail (Video Game)",
        "league of legends": "League of Legends",
        "overwatch": "Overwatch (Video Game)",
        "stranger things": "Stranger Things (TV 2016)",
        "the witcher": "The Witcher (TV)",
        "succession": "Succession (TV 2018)",
        "ted lasso": "Ted Lasso (TV)",
        "our flag means death": "Our Flag Means Death (TV)",
        "bridgerton": "Bridgerton (TV)",
        "the bear": "The Bear (TV 2022)",
        "house md": "House M.D.",
        "criminal minds": "Criminal Minds (US TV)",
        "9-1-1": "9-1-1 (TV)",
        "911 lone star": "9-1-1: Lone Star (TV)",
        "wednesday": "Wednesday (TV 2022)",
        "interview with the vampire": "Interview with the Vampire (TV 2022)",
        "rwby": "RWBY",
        "k-pop": "K-pop",
        "kpop": "K-pop",
        "bts": "방탄소년단 | Bangtan Boys | BTS",
        "ateez": "ATEEZ (Band)",
        "stray kids": "Stray Kids (Band)",
        "the magnus archives": "The Magnus Archives (Podcast)",
        "the magnus protocol": "The Magnus Protocol (Podcast)",
        "wolf 359": "Wolf 359 (Radio)",
        "critical role": "Critical Role (Web Series)",
        "dimension 20": "Dimension 20 (Web Series)",
    ]

    static let languageAliases: [String: String] = [
        "english": "en",
        "in english": "en",
        "spanish": "es",
        "in spanish": "es",
        "en español": "es",
        "french": "fr",
        "in french": "fr",
        "en français": "fr",
        "german": "de",
        "in german": "de",
        "auf deutsch": "de",
        "russian": "ru",
        "in russian": "ru",
        "chinese": "zh",
        "in chinese": "zh",
        "japanese": "ja",
        "in japanese": "ja",
        "korean": "ko",
        "in korean": "ko",
        "portuguese": "pt",
        "italian": "it",
    ]
}
